Acrossud/Acrossud/Controllers/EntitiesController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Acrossud.Models;
using Newtonsoft.Json;

namespace Acrossud.Controllers
{
    [Authorize]
    public class EntitiesController : Controller
    {
        public string GetBaseUrl()
        {
            string result = string.Format("{0}/", Request.Url.GetLeftPart(UriPartial.Authority));

            return result;
        }

        // GET: Entities
        public ActionResult Index()
        {
            EntityCollectionModel model = new EntityCollectionModel();
            model.Entities = EntityMger.Instance.GetEntities();

            foreach (Entity entity in model.Entities)
            {
                entity.Properties = EntityMger.Instance.GetValueOfPropertiesByEntityId(entity.Id);
            }

            return View(model);
        }

        #region Creation
        public ActionResult CreateNew()
        {
            EntityModel model = new EntityModel();
            model.Properties = EntityMger.Instance.GetProperties().Where(p => p.Name != EnumConst.PropertyNameMainPicture).ToList();
            return View(model);
        }

        [HttpPost]
        public ActionResult CreateNew(EntityModel model)
        {
            Entity entity = new Entity();
            entity.Name = model.Name;
            entity.Description = model.Description == null ? String.Empty : model.Description;
            entity.Id = EntityMger.Instance.CreateEntity(entity);

            if (entity.Id > 0)
            {
                foreach (Property property in model.Properties)
                {
                    EntityProperty ep = new EntityProperty();
                    ep.EntityId = entity.Id;
                    ep.PropertyId = property.Id;
                    ep.Value = property.Value;
                    ep.Id = EntityMger.Instance.AddOrUpdateEntityProperty(ep);
                }

                string path = new DirectoryInfo(string.Format(EnumConst.EntityImagesPath, Server.MapPath("/"), entity.Id.ToString())).ToString();

                string thumbnail_path = string.Format(EnumConst.EntityThumbnailImagesPath, path, entity.Id.ToString());

                if (!Directory.Exists(path))
                    Directory.CreateDirectory(path);

                if (!Directory.Exists(thumbnail_path))
                    Directory.CreateDirectory(thumbnail_path);

                return RedirectToAction("GetEntityDocument", new {entity_name = entity.Name, entity_id = entity.Id });
            }
            else
                return RedirectToAction("Index");
        }
        #endregion

        #region Edition
        public ActionResult EditEntity(int entity_id)
        {
            Entity entity = EntityMger.Instance.GetEntity(entity_id);

            EntityModel model = new EntityModel()
            {
                Id = entity.Id,
                Name = entity.Name,
                Description = entity.Description
            };

            model.Properties = EntityMger.Instance.GetValueOfPropertiesByEntityId(entity_id);
            return View(model);
        }

        [HttpPost]
        public ActionResult EditEntity(EntityModel model)
        {
            Entity entity = new Entity();
            entity.Name = model.Name;
            entity.Description = model.Description == null ? String.Empty : model.Description;
            entity.Id = model.Id;
            int result = EntityMger.Instance.UpdateEntity(entity);

            foreach (Property property in model.Properties)
            {
                EntityProperty ep = new EntityProperty();
                ep.EntityId = entity.Id;
                ep.PropertyId = property.Id;
                ep.Value = property.Value;
                result = EntityMger.Instance.AddOrUpdateEntityProperty(ep);
            }

            return RedirectToAction("Index", new { alert_title = "Cambios guardados", alert = "Se han guardado los cambios con éxito." });
        }

        public ActionResult Delete(int entity_id)
        {
            string path = new DirectoryInfo(string.Format(EnumConst.EntityImagesPath, Server.MapPath("/"), entity_id.ToString())).ToString();

            if (Directory.Exists(path))
            {
                Directory.Delete(path, true);
            }

            int result = EntityMger.Instance.DeleteEntity(entity_id);

            return RedirectToAction("Index", new { alert_title = "Propiedad eliminada", alert = "Se ha eliminado la propiedad con éxito." });
        }
        #endregion

        #region Documents
        public ActionResult GetEntityDocument(string entity_name, int entity_id)
        {
            ViewBag.EntityName = entity_name;
            ViewBag.EntityId = entity_id;
            return View();
        }

        public ActionResult AddEntityDocument(int entity_id)
        {
            bool isSavedSuccessfully = true;
            string file_name = String.Empty;
            try
            {
                foreach (string fileName in Request.Files)
                {
                    HttpPostedFileBase file = Request.Files[fileName];

                    if (file != null && file.ContentLength > 0)
                    {
                        file_name = file.FileName;

                        string path = new DirectoryInfo(string.Format(EnumConst.EntityImagesPath, Server.MapPath("/"), entity_id.ToString())).ToString();

                        string thumbnail_path = string.Format(EnumConst.EntityThumbnailImagesPath, path, entity_id.ToString());

                        string absolute_file_name = string.Format(EnumConst.AbsoluteFileName, path, file_name);

                        if (!Directory.Exists(path))
                            Directory.CreateDirectory(path);

                        if (!Directory.Exists(thumbnail_path))
                            Directory.CreateDirectory(thumbnail_path);

                        if (Directory.GetFiles(path).Where(f => f != EnumConst.ThumbnailDir).Count() == 0)
                        {
                            Property p = EntityMger.Instance.GetPropertyByName(EnumConst.PropertyNameMainPicture);
                            EntityProperty ep = new EntityProperty();
                            ep.EntityId = entity_id;
                            ep.PropertyId = p.Id;
                            ep.Value = file_name;
                            ep.Id = EntityMger.Instance.AddOrUpdateEntityProperty(ep);
                        }

                        Bitmap bitmap = Utilities.IsImage(file);

                        if (bitmap != null)
                        {
                            int thumb_height = EnumConst.ThumbnailDefaultSize;
                            int thumb_width = EnumConst.ThumbnailDefaultSize;

                            if (bitmap.Height > bitmap.Width)
                            {
                                thumb_width = (int) (bitmap.Width * ((float)thumb_height / (float)bitmap.Height));
                            }
                            else
                            {
                                thumb_height = (int) (bitmap.Height * ((float)thumb_width / (float)bitmap.Width));
                            }

                            Image thumbnail = bitmap.GetThumbnailImage(thumb_width, thumb_height, null, IntPtr.Zero);
                            thumbnail.Save(string.Format(EnumConst.AbsoluteFileName, thumbnail_path, file_name));
                            thumbnail.Dispose();
                            bitmap.Dispose();
                        }

                        file.SaveAs(absolute_file_name);
                    }
                }
            }
            catch (Exception ex)
            {
                isSavedSuccessfully = false;
                return Json(new { Message = ex.Message + " - Stacktrace: " + ex.InnerException + ex.StackTrace });
            }

            if (isSavedSuccessfully)
            {
                return Json(new { Message = file_name });
            }
            else
            {
                return Json(new { Message = "Hubo un error al guardar el archivo" });
            }
        }

        public JsonResult GetEntityDocumentsFiles(int entity_id)
        {
            List<EntityDocumentFileInfo> result = new List<EntityDocumentFileInfo>();

            string path = new DirectoryInfo(string.Format(EnumConst.EntityImagesPath, Server.MapPath("/"), entity_id.ToString())).ToString();

            if (Directory.Exists(path))
            {
                var folder = new DirectoryInfo(path);

                FileInfo[] files = folder.GetFiles();

                for (int i = 0; i < files.Length; i++)
                {
                    FileInfo file = files[i];
                    string url_file = string.Format(EnumConst.EntityImagesPath, GetBaseUrl(), entity_id);
                    url_file = string.Format(EnumConst.EntityThumbnailImagesPath, url_file);
                    url_file = string.Format(EnumConst.AbsoluteFileName, url_file, file.Name);
                    result.Add(new EntityDocumentFileInfo() { FileName = file.Name, Path = url_file, FileSize = file.Length });
                }
            }

            var jSonSerialize = new JavaScriptSerializer();

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public void DeleteEntityDocumentFile(int entity_id, string file_name)
        {
            string path = new DirectoryInfo(string.Format(EnumConst.EntityImagesPath, Server.MapPath("/"), entity_id.ToString())).ToString();

            string thumbnail_path = string.Format(EnumConst.EntityThumbnailImagesPath, path, entity_id.ToString());

            string absolute_file_name = string.Format(EnumConst.AbsoluteFileName, path, file_name);

Acrossud/Acrossud/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Acrossud.Models;

namespace Acrossud.Controllers
{
    public class HomeController : Controller
    {
        public string GetBaseUrl()
        {
            string result = string.Format("{0}/", Request.Url.GetLeftPart(UriPartial.Authority));

            return result;
        }

        private List<Property> SetPropertiesToShow(List<Property> properties)
        {
            List<Property> result = properties.Where(p =>
                                        p.Name != EnumConst.PropertyNameFeatured &&
                                        p.Name != EnumConst.PropertyNameActive &&
                                        p.Name != EnumConst.PropertyNameMainPicture)
                                    .ToList().OrderBy(p => p.Order).ToList();

            Property price_property = properties.FirstOrDefault(p => p.Name == EnumConst.PropertyNamePrice);
            Property price_property_gc = properties.FirstOrDefault(p => p.Name == EnumConst.PropertyNamePriceGc);

            if (price_property != null)
            {
                price_property.Value = Views.Helpers.Helpers.GetEntityPrice(price_property, properties.FirstOrDefault(p => p.Name == EnumConst.PropertyNameCurrency));
            }

            if (price_property_gc != null)
            {
                price_property_gc.Value = Views.Helpers.Helpers.GetEntityPrice(price_property_gc, properties.FirstOrDefault(p => p.Name == EnumConst.PropertyNameCurrencyGc));
            }

            return result;
        }

        public ActionResult Index()
        {
            EntityCollectionModel model = new EntityCollectionModel();
            model.Entities = EntityMger.Instance.GetEntitiesFiltered(EnumConst.PropertyNameFeatured, EnumConst.PropertyOperator.Equal, EnumConst.PropertyValue.True);

            foreach (Entity entity in model.Entities)
            {
                entity.Properties = EntityMger.Instance.GetValueOfPropertiesByEntityId(entity.Id);
            }

            return View(model);
        }

        public ActionResult ShowEntity(int entity_id)
        {
            Entity entity = EntityMger.Instance.GetEntity(entity_id);

            EntityModel model = new EntityModel()
            {
                Id = entity.Id,
                Name = entity.Name,
                Description = entity.Description
            };

            model.Properties = SetPropertiesToShow(EntityMger.Instance.GetValueOfPropertiesByEntityId(entity_id));

            string path = new DirectoryInfo(string.Format(EnumConst.EntityImagesPath, Server.MapPath("/"), entity_id.ToString())).ToString();

            model.Documents = new List<EntityDocumentFileInfo>();

            if (Directory.Exists(path))
            {
                List<string> documents = Directory.GetFiles(path).Where(f => f != EnumConst.ThumbnailDir).ToList();

                string url_file = String.Empty;
                string url_file_thumbnail = String.Empty;
                int width = EnumConst.ImageDefaultWidth;
                int height = EnumConst.ImageDefaultHeight;

                foreach (string document in documents)
                {
                    url_file = string.Format(EnumConst.EntityImagesPath, GetBaseUrl(), entity_id);
                    url_file = string.Format(EnumConst.AbsoluteFileName, url_file, Path.GetFileName(document));

                    url_file_thumbnail = string.Format(EnumConst.EntityImagesPath, GetBaseUrl(), entity_id);
                    url_file_thumbnail = string.Format(EnumConst.EntityThumbnailImagesPath, url_file_thumbnail);
                    url_file_thumbnail = string.Format(EnumConst.AbsoluteFileName, url_file_thumbnail, Path.GetFileName(document));

                    try
                    {
                        Bitmap image = (Bitmap)Image.FromFile(document);
                        width = image.Width;
                        height = image.Height;
                        image.Dispose();
                    }
                    catch (Exception ex)
                    {

                    }

                    model.Documents.Add(new EntityDocumentFileInfo() { ThumbnailFilename = url_file_thumbnail, FileName = url_file, Height = height, Width = width });
                }
            }

            return View(model);
        }

        public ActionResult GetAllActiveEntities()
        {
            EntityCollectionModel model = new EntityCollectionModel();
            model.Entities = EntityMger.Instance.GetEntitiesFiltered(EnumConst.PropertyNameActive, EnumConst.PropertyOperator.Equal, EnumConst.PropertyValue.True);

            foreach (Entity entity in model.Entities)
            {
                entity.Properties = EntityMger.Instance.GetValueOfPropertiesByEntityId(entity.Id);
            }

            return View(model);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }
    }
}

Acrossud/Acrossud/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Acrossud/Acrossud/Views/Home/Contact.cshtml
<div class="main-title-wrapper">
    <h2 id="contacto" class="main-title">Contacto</h2>
</div>

<div class="row-fill">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                <form id="contact-me-form" action="http://formspree.io/abriano@acrossud.com.uy" method="POST">
                    <h4 id="name-label">Nombre</h4>
                    <input id="name-input" type="text" name="_name_reply">
                    <h4 id="email-label">E-mail</h4>
                    <input id="email-input" type="email" name="_reply_to">
                    <h4 id="msg-label">Mensaje</h4>
                    <textarea id="msg-textarea" name="_body"></textarea>
                    <input type="hidden" name="_next" value="http://www.m6.com.uy?success-msg=true#contact-me">
                    <input class="btn btn-default" id="btn-input" type="submit" value="Enviar" name="_submit">
                </form>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                <div id="social-network-wrapper">
                    <div class="col-lg-12">
                        <a class="link-address" href="https://www.facebook.com/brianoalicia">
                            <img width="40" height="40" src="@Url.Content("~/images/facebook_icon.png")" />
                            <span>/brianoalicia</span>
                        </a>
                    </div>
                    <div class="col-lg-12">
                        <div class="link-address">
                            <img width="40" height="40" src="@Url.Content("~/images/whatsapp_icon.png")" />
                            <span>098 732 756</span>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <a class="link-address" href="mailto:abriano@acrossud.com">
                            <img width="40" height="30" src="@Url.Content("~/images/email_icon.png")" />
                            <span>abriano@acrossud.com</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Acrossud/Acrossud/Views/Home/GetAllActiveEntities.cshtml
@{
    ViewBag.Title = "GetAllActiveEntities";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (Request.IsAuthenticated)
{
    <div class="text-right" style="margin:10px;">
        @Html.ActionLink("Cambiar a vista edición", "Index", "Entities", null, new { @class = "btn btn-info text-right" })
    </div>
}
<div class="index-entities-wrapper">
    @Html.Partial("EntitiesCollection")
</div>

Acrossud/Acrossud/Views/Home/Index.cshtml
@using Acrossud.Views.Helpers;
@{
    ViewBag.Title = "Acrossud";
}

<div class="jumbotron">
    <p>Podrás encontrar la propiedad que más se adapte a tus necesidades.
    <br/>
    <br />
    Tenemos la experiencia, seriedad y responsabilidad en la mejor atención.</p>
</div>

<div class="main-title-wrapper">
    <h2 class="main-title">Destacadas</h2>
</div>
<div class="index-entities-wrapper">
    @Html.Partial("EntitiesCollection")
    <a class="col-xs-12 col-sm-6 col-md-4 col-lg-4 vcenter index-entity-wrapper" href="@Url.Action("GetAllActiveEntities")">
        <div id="more-properties-cell">Ver más</div>
    </a>
</div>

@Html.Partial("Contact")

Acrossud/Acrossud/Views/Home/ShowEntity.cshtml
@model Acrossud.Models.EntityModel
@using Acrossud.Views.Helpers;
@using Acrossud.Models;
@{
    ViewBag.Title = "ShowEntity";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="col-md-10 col-lg-8 col-md-offset-1 col-lg-offset-2">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <h2>@Model.Name</h2>
        </div>
    </div>
    @{
        if (Model.Documents.Count > 0)
        {
            <div class="row">
                <div class="entity-gallery-wrapper">
                    <div class="entity-gallery">
                        @{
                            foreach (EntityDocumentFileInfo image in Model.Documents)
                            {
                                <a href="@image.FileName" data-size="@string.Format("{0}x{1}",image.Width,image.Height)">
                                    <img src="@image.ThumbnailFilename" alt="">
                                </a>
                            }
                        }
                    </div>
                </div>
            </div>
        }
    }
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
            <p><strong>Descripción</strong></p>
            <p>@Model.Description</p>
        </div>
    </div>
    <div class="row">
        @{
            var count = Model.Properties.Count();
            for (var i = 0; i < count; i++)
            {
                if (i == 0 || i == (count / 2) + 1)
                {
                    @:<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                }
                <div class="form-group row">
                    <div class="col-md-4">
                        <label class="control-label " for="Name">@Model.Properties[i].Name</label>
                    </div>
                    <div class="col-md-8">
                        @Helpers.GetPropertyValue(Model.Properties[i])
                    </div>
                </div>

                if ((i == count / 2) || i == count - 1)
                {
                    @:</div>
                }
            }
        }
    </div>
</div>